[package]
name = "_durak_core"
version = "0.4.0"
edition = "2021"

[lib]
name = "_durak_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27", features = ["extension-module"] }
regex = "1.10"
